# Generated by Django 3.2.18 on 2023-04-21 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField(default=1578384000)),
                ('sunrise', models.BigIntegerField(default=1578384000)),
                ('sunset', models.BigIntegerField(default=1578384000)),
                ('wind_speed', models.IntegerField(default=0)),
                ('wind_deg', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(default=32608)),
                ('user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Temperature Forecast', max_length=64)),
                ('range', models.CharField(choices=[('h', 'hourly'), ('d', 'daily')], default='h', max_length=1)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.forecast')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('time', models.BigIntegerField()),
                ('forecastTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.forecasttable')),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.summary'),
        ),
        migrations.CreateModel(
            name='ConditionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_title', models.CharField(default='Conditions', max_length=64)),
                ('date', models.BigIntegerField(default=1578384000)),
                ('average_temp', models.IntegerField(default=0)),
                ('feels_like', models.IntegerField(default=1)),
                ('pressure', models.IntegerField(default=2)),
                ('humidity', models.IntegerField(default=3)),
                ('wind_speed', models.IntegerField(default=4)),
                ('pop', models.IntegerField(default=5)),
                ('rain_levels', models.IntegerField(default=6)),
                ('weather_name', models.CharField(default='Rain', max_length=64)),
                ('icon', models.CharField(default='10n', max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.summary')),
            ],
        ),
    ]
