# Generated by Django 3.2.18 on 2023-04-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62)),
                ('date', models.BigIntegerField()),
                ('averageTemp', models.IntegerField()),
                ('feelsLike', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('windSpeed', models.IntegerField()),
                ('pop', models.IntegerField()),
                ('rainLevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConditionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62)),
                ('date', models.BigIntegerField()),
                ('averageTemp', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('pop', models.IntegerField()),
                ('rain_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conditionset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62)),
                ('date', models.BigIntegerField()),
                ('averageTemp', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('pop', models.IntegerField()),
                ('rain_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temp', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('pop', models.IntegerField()),
                ('rain_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62)),
                ('temp', models.CharField(max_length=255)),
                ('date', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayConditions2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62)),
                ('date', models.BigIntegerField()),
                ('averageTemp', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('pop', models.IntegerField()),
                ('rain_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField()),
                ('sunrise', models.IntegerField()),
                ('sunset', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('wind_deg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('range', models.CharField(choices=[('h', 'hourly'), ('d', 'daily')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
    ]
