# Generated by Django 3.2.18 on 2023-04-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastrow',
            name='time',
            field=models.BigIntegerField(),
        ),
    ]
