# Generated by Django 3.2.18 on 2023-04-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_title', models.CharField(default='Conditions', max_length=64)),
                ('date', models.BigIntegerField(default=1578384000)),
                ('average_temp', models.IntegerField(default=0)),
                ('feels_like', models.IntegerField(default=1)),
                ('pressure', models.IntegerField(default=2)),
                ('humidity', models.IntegerField(default=3)),
                ('wind_speed', models.IntegerField(default=4)),
                ('pop', models.IntegerField(default=5)),
                ('rain_levels', models.IntegerField(default=6)),
                ('weather_name', models.CharField(default='Rain', max_length=64)),
                ('icon', models.CharField(default='10n', max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.summary')),
            ],
        ),
        migrations.DeleteModel(
            name='ConditionsList',
        ),
    ]
