# Generated by Django 3.2.18 on 2023-04-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_forecastrow_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
