# Generated by Django 3.2.18 on 2023-04-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20230418_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionslist',
            name='widget_title',
            field=models.CharField(default='Conditions', max_length=64),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='average_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='date',
            field=models.BigIntegerField(default=1578384000),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='feels_like',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='humidity',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='pop',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='pressure',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='rain_level',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='conditionslist',
            name='wind_speed',
            field=models.IntegerField(default=4),
        ),
    ]
