# Generated by Django 3.2.18 on 2023-04-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20230418_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionslist',
            name='unix_date',
            field=models.BigIntegerField(default=1578384000),
        ),
    ]
