# Generated by Django 3.2.18 on 2023-04-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20230422_0509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summary',
            new_name='Page',
        ),
        migrations.DeleteModel(
            name='SearchResults',
        ),
    ]
