# Generated by Django 3.2.18 on 2023-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20230422_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_title',
            field=models.CharField(default='Summary', max_length=64),
        ),
    ]
