# Generated by Django 3.2.18 on 2023-04-18 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_conditionslist_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionslist',
            name='date',
        ),
    ]
