# Generated by Django 3.2.18 on 2023-04-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_page_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='sunrise',
            field=models.BigIntegerField(default=1684059299),
        ),
        migrations.AddField(
            model_name='conditions',
            name='sunset',
            field=models.BigIntegerField(default=1684106099),
        ),
    ]
