# Generated by Django 3.2.18 on 2023-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_rename_unix_date_conditionslist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='location',
            field=models.IntegerField(default=32608),
        ),
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
