# Generated by Django 3.2.18 on 2023-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='city',
            field=models.CharField(default='Gainesville', max_length=64),
        ),
    ]
