# Generated by Django 3.2.18 on 2023-04-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_page_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='pop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='rain_levels',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
