# Generated by Django 3.2.18 on 2023-04-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_auto_20230418_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasttable',
            name='forecast',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logic.forecast'),
            preserve_default=False,
        ),
    ]
