# Generated by Django 3.2.18 on 2023-04-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_auto_20230427_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastrow',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
