# Generated by Django 3.2.18 on 2023-04-18 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_auto_20230418_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrow',
            name='forecastTable',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logic.forecasttable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecasttable',
            name='range',
            field=models.CharField(choices=[('h', 'hourly'), ('d', 'daily')], default='h', max_length=1),
        ),
        migrations.AlterField(
            model_name='forecasttable',
            name='type',
            field=models.CharField(default='Temperature Forecast', max_length=64),
        ),
    ]
