# Generated by Django 3.2.18 on 2023-04-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_auto_20230420_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='forecast',
        ),
        migrations.AddField(
            model_name='forecast',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logic.summary'),
            preserve_default=False,
        ),
    ]
